### ISSUE TITLE
Hi/Low Temp Display Option

### ISSUE THREAD

**Issue by atatistcheff** [ThingPulse/esp8266-weather-station#108]
This is a suggested enhancement to the forecast high/low temp display.  Here in the U.S. we are used to the high temp showing before the low temp.  For example a high of 70 and a low of 45 would be shown as 70/45.  In the weather station library they are displayed as low/high (45/70).  Right now this requires modifying the library code to swap these values.  

Of course if I missed some other easy method to do this please accept my apologies and let me know what it is.  Thanks!

**Comment by sungkhum** [comment]
Yes, I agree - this would be a great feature. Here's some code that has the general idea: https://github.com/zagortenay333/Harmattan/blob/master/.harmattan-assets/parse_weather
I'll try putting something together.
