### ISSUE TITLE
WeatherConditionDemo - Boot Loop at ESP12E

### ISSUE THREAD

**Issue by njordan77** [ThingPulse/esp8266-weather-station#109]
hi,
i once used the PlainDemo which worked fine (about 1 year ago). Today i used the renamed ConditionDemo which after uploaded does boot looping. Tried it with 3 different Wemos and NodeMCU boards....

Using Core 2.4.1 + the latest JSONlistener and WeatherStation library....

Any idea if this is known and can be fixed easily? From the issue list this seems to not happen before....

**Comment by mnbrgr** [comment]
I'am using the WeatherStationDemo and observe the same issue.
