### ISSUE TITLE
Halts on forecast update

### ISSUE THREAD

**Issue by vegos** [ThingPulse/esp8266-weather-station#111]
I noticed that on an ESP07, after some hours, it halts on updating forecasts.
It stays forever on the "Updating forecast" screen...

Same code, has no problems on other ESP modules...

**Comment by marcelstoer** [comment]
Are the modules all on the same ESP8266 Arduino core version? I sometimes observe such behavior with certain APs and Arduino 2.4.1, downgrading to 2.3 resolved it.

**Comment by vegos** [comment]
I'll try to downgrade, and check if it fixes the problem...
