### ISSUE TITLE
Wunderground will no longer provide free weather API keys

### ISSUE THREAD

**Issue by glen4cindy** [ThingPulse/esp8266-weather-station#113]
API keys are no longer available from Wunderground. According to Wunderground "for the time being, free keys will continue to work.  We will update you if that changes." 

Is it possible to program another provider such as AccuWeather or OpenWeather Map?

I'm not really a programmer so how would one go about changing the provider for this weather station?

Thanks in advance.

**Comment by marcelstoer** [comment]
Yep, stay tuned, we're working on it: https://thingpulse.com/weather-underground-no-longer-providing-free-api-keys/
