### ISSUE TITLE
How to load and use Open Weather Map instead of Weather Underground

### ISSUE THREAD

**Issue by glen4cindy** [ThingPulse/esp8266-weather-station#115]
Please pardon the newbie questions.

I neglected to obtain an API key from WU when I first signed up with them. Then a few days later when my hardware arrived they discontinued issuing them.

I now have an API key from OWM, but, I am not sure where to put this or how to make sure it uses OWM.

I can see plenty of modifications have been made to this. Is it not quite ready to run without WU? or am I missing some directions somewhere?

Thanks in advance.

**Comment by marcelstoer** [comment]
The documentation was updated: https://docs.thingpulse.com/guides/iot-starter-kit/ (pages 30ff)
