### ISSUE TITLE
OpenWeatherMapCurrent.cpp - Pressure not converted by OWM when Imeprial requested

### ISSUE THREAD

**Issue by G6EJD** [ThingPulse/esp8266-weather-station#116]
Extract from API:

pressure  Atmospheric pressure (on the sea level, if there is no sea_level or grnd_level data) hPa  hPa  hPa  

Please note: When Imperial units are requested, air pressure is not converted to 'ins ' it remains in hPa

Same for OpenWeatherMapForecast

I can't see anywhere where you make the conversion, I may have missed it.

**Comment by squix78** [comment]
So you would expect that we convert the value even if the OpenWeatherMap API thinks it's not necessary? I kind of feel that it is rather a bug in the OpenWeatherMap API than in ours. We tell OWM that we want all values in imperial system and they return pressure in hPa. However, I see that this might be unexpected for people used to the imperial system. Can you provide documentation which unit should be used and how we can convert hPa to that unit (ins, psi?)? Is this a simple linear conversion? Is it clear for everybody using the imperial system that air pressure is provided in this unit and not in hPa? I wouldn't like to fix it for only a part of the "imperial users" and break it for the others...

**Comment by G6EJD** [comment]
I was checking my code today and thought I’d check M versus I units and Irma seems and according to the API documentation that only some units are converted, so we have pressure in hPa, rainfall in mm not converted but wind speed in m/S becomes mph. All the conversions are linear and a simple multiplier converts hPa to inches of Mercury, I really think it’s time for the US to convert to metric, ironically most of their science community uses the SI units. I can’t think of any other units than imperial or another country that uses imperial than the US, but not a market to ignore I think.
