### ISSUE TITLE
No Weather Data

### ISSUE THREAD

**Issue by jlrw** [ThingPulse/esp8266-weather-station#117]
Hello. I set up the weather station demo, no problems compiling. But, I receive no weather data. It only shows 0C and no forecasts. Any idea why this might be happening?

**Comment by mimiflynn** [comment]
Did you get an API key and add it to the variables in the sketch?

**Comment by jlrw** [comment]
Yes. I set it up again at home on a different computer and it worked just
fine...not sure what the problem was with the other computer. Perhaps it
wasn't configured for the particular type of ESP8266 that I had...
