### ISSUE TITLE
OLED Library missing

### ISSUE THREAD

**Issue by Georgeeden** [ThingPulse/esp8266-weather-station#119]
Hello,

For some reason a have a load of libraries missing and it is impossible for me to get the same ones, could you please help.

The error I receive is "#include "SSD1306Wire.h"

Heres a screenshot of the IDE (I am using the default Arduino IDE) http://prntscr.com/jvqycv

Kind Regards,

George

**Comment by pacraf** [comment]
Just put SSD1306Wire.h in Google search. First result is GitHub project where this lib is originated. Cheers.
