### ISSUE TITLE
enhancement request: make localization for other languages

### ISSUE THREAD

**Issue by tueddy** [ThingPulse/esp8266-weather-station#12]
Hello,

nice widget/library!
Is it possible to make it with localization for other countries?
Currently some strings are hardcoded in english.
Suggestion: Do it with include files & ProgMem:

include in main file (.ino)

// Valid values: 
// - "language_EN.h" for (English)
//
# define LANGUAGE_FILE "language_DE.h"

And language files like this:

 // Messages list  
const prog_char PROGMEM MSG_LANGUAGE_CODE[] =                     "EN";
const prog_char PROGMEM MSG_HUMINITY[] =                      "Huminity"

Best regards
Dirk

**Comment by stony2k** [comment]
Is there a advantage for ProgMem instead of classic strings?

**Comment by marcelstoer** [comment]
> Is there a advantage for ProgMem instead of classic strings?

http://playground.arduino.cc/Learning/Memory, you usually have flash memory in abundance but SRAM is often a scarce resource.

As for the original request, we happily accept PRs for such features.  Related to https://github.com/ThingPulse/esp8266-weather-station-color/issues/34.
