### ISSUE TITLE
A ^

### ISSUE THREAD

**Issue by tedbmoss** [ThingPulse/esp8266-weather-station#123]
there is an A with a hat on it in line 386 for local temp before the F or C . what is this for? I removed it.
I can't see where you have the q to ask for weather data, it is there and works, but I can't tell where it comes from, a font number perhaps? I would like to replace it with id so I can call my local weather, Peoria, AZ since Peoria is ambiguous.

**Comment by ccpetersen** [comment]
The "q=" is hardcoded in the OpenWeatherMapCurrent.cpp and OpenWeatherMapForecast.ccp around line 35. Change it to "id=". and you should be good to go.

**Comment by marcelstoer** [comment]
> there is an A with a hat on it in line 386 for local temp before the F or C 

In which file?

> so I can call my local weather, Peoria, AZ since Peoria is ambiguous.

I created PR #122 for exactly that problem.

**Comment by marcelstoer** [comment]
This appears to be about https://github.com/ThingPulse/esp8266-weather-station-color/blob/master/esp8266-weather-station-color.ino#L386. Works fine in all editors and all platforms we tested (Windows/Mac).

**Comment by tedbmoss** [comment]
In reference to the degree symbols C and F. Sorry about this, but the file published has a different symbol in it than the (later) one in the referenced file which works fine. I copied it from the file which you referenced and it does as you say, but the one published does not. I don't know how to say this to make it clearer, I know it could be said better.
