### ISSUE TITLE
City ID instead of City Name

### ISSUE THREAD

**Issue by SWEUSPeter** [ThingPulse/esp8266-weather-station#128]
Here across the pond we have several towns with the same name and the result from OpenWeather isn't always coming back with result for the correct town. Per OpenWeather API documentation they recommend using City ID vs City name. Any chance this could be incorporated in a future release of this great product!

**Comment by marcelstoer** [comment]
Yep, you're preaching to the choir... I noticed this shortcoming a while and created #122. Will land soon.
