### ISSUE TITLE
weather station demo extended

### ISSUE THREAD

**Issue by w5tmp** [ThingPulse/esp8266-weather-station#129]
Arduino: 1.8.5 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\wclarc-laptop1\Documents\Arduino\WeatherStationDemo_SHED\WeatherStationDemo_SHED.ino: In function 'void setup()':

WeatherStationDemo_SHED:153: error: 'activeSymbole' was not declared in this scope

     display.drawXbm(46, 30, 8, 8, counter % 3 == 0 ? activeSymbole : inactiveSymbole);

                                                      ^

WeatherStationDemo_SHED:153: error: 'inactiveSymbole' was not declared in this scope

     display.drawXbm(46, 30, 8, 8, counter % 3 == 0 ? activeSymbole : inactiveSymbole);

                                                                      ^

WeatherStationDemo_SHED:163: error: 'activeSymbole' was not declared in this scope

   ui.setActiveSymbol(activeSymbole);

                      ^

WeatherStationDemo_SHED:164: error: 'inactiveSymbole' was not declared in this scope

   ui.setInactiveSymbol(inactiveSymbole);

                        ^

exit status 1
'activeSymbole' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by marcelstoer** [comment]
`WeatherStationDemo_SHED.ino` -> none of our sketches
