### ISSUE TITLE
When the json streams are incomplete, add delay(0 or 1) in the streaming loops

### ISSUE THREAD

**Issue by VeryBitter** [ThingPulse/esp8266-weather-station#131]
### Missing feature
Hello
I spend quite a lot of time figuring out why the parsed streams from openweathermap (and my own) were incomplete. It is related to how the WiFi and TCP/IP libraries handle the pending events. Basically they wait to handle them only after the end of a loop (except when delay()is called). That affects the http connection. From [http://arduino.esp8266.com/versions/1.6.5-947-g39819f0/doc/reference.html](url) you get

> Remember that there is a lot of code that needs to run on the chip besides the sketch when WiFi is connected. WiFi and TCP/IP libraries get a chance to handle any pending events each time the loop() function completes, OR when delay is called. If you have a loop somewhere in your sketch that takes a lot of time (>50ms) without calling delay, you might consider adding a call to delay function to keep the WiFi stack running smoothly.

>There is also a yield() function which is equivalent to delay(0). The delayMicroseconds function, on the other hand, does not yield to other tasks, so using it for delays more than 20 milliseconds is not recommended.

### Justification
To get the full streams, obviously

### Workarounds

Add delay(0) or delay(1) and increase lostTest variable in the loop `while((size = client->available()) > 0){` in the _doupdate_ function

```c
while(client->connected()) {
  while((size = client->available()) > 0) {
    if ((millis() - lost_do) > lostTest) {
      Serial.println ("lost in client with a timeout");
      client->stop();
      ESP.restart();
    }
    c = client->read();
    if (c == '{' || c == '[') {
      isBody = true;
    }
    if (isBody) {
      parser.parse(c);
    }
    delay(0); // <---------
  }
}
```

Actually not sure which one is the best delay(0) or delay(1)
Hope I can help.

Aristide

**Comment by marcelstoer** [comment]
Thanks, when I was working on https://support.thingpulse.com/743/no-city-name-on-display-weather-colour I had a hunch that something like this may be the root cause.

**Comment by VeryBitter** [comment]
Actually, without the delay(0), the size was systematically wrong (smaller). I suspect that the size might increase (and not just decrement by one) as more stream is fed by the server thanks to `size = client->available())`. BTW the delay() should be in the `while((size = client->available()) > 0)` not in the upper loop. I try to correct my first contribution.

**Comment by Tiogaplanet** [comment]
@VeryBitter thank you for your post.  I was experiencing the exact same problem with Naples, Italy (3172394).  Your fix of `delay(0)` fixed the problem for me.

**Comment by Tiogaplanet** [comment]
Well, not a perfect solution...still get bad values for wind degrees even when using `delay(15)`.  I am using an iPhone hotspot for my tests so that may play a role too.

**Comment by marcelstoer** [comment]
Thanks a lot for the fix @VeryBitter, much appreciated!

**Comment by VeryBitter** [comment]
@Tiogaplanet  if you increase the delay, then you have to increase the lostTest variable to give enough time to the stream parser to process all the info.

**Comment by Tiogaplanet** [comment]
@VeryBitter, yes, I figured that out but the `yield()` fix works just fine so I'm not going to sweat it anymore.  Thank you for the advice and for making this thread.  It was very helpful.
