### ISSUE TITLE
library problem

### ISSUE THREAD

**Issue by cecconilorenzo** [ThingPulse/esp8266-weather-station#132]
hello, I have a problem in the new version, I'm trying to use the example (WeatherStationDemo) but when I load it I get this error: fatal error:
coredecls.h: No such file or directory

 #include <coredecls.h> // settimeofday_cb ()

I can not solve the problem.

**Comment by marcelstoer** [comment]
This file comes with ESP8266 Arduino core: https://github.com/esp8266/Arduino/blob/master/cores/esp8266/coredecls.h
