### ISSUE TITLE
Use of long with millis()

### ISSUE THREAD

**Issue by ricatelli** [ThingPulse/esp8266-weather-station#133]
Hello, the use of variables of type long with millis() must be corrected in some libraries and examples. They must be **unsigned long** for prevent errors in roll over. Thanks.

**Comment by marcelstoer** [comment]
> in some libraries

What do you mean by _some_ libraries, can you clarify? There is only 1 library in this repository.

**Comment by ricatelli** [comment]
I mean some files like TimeClient.h or WorldClockClient.h
