### ISSUE TITLE
WorldClockClient stoped working

### ISSUE THREAD

**Issue by rverzinkevicius** [ThingPulse/esp8266-weather-station#136]
Part below stopped working and is not returning time anymore

WorldClockClient.cpp

// http://api.thingspeak.com/channels/CHANNEL_ID/feeds.json?results=2&api_key=API_KEY
  const char host[] = "oleddisplay.squix.ch";
  String url = "/rest/time";

**Comment by Matz88** [comment]
I have solved reverting timeclient.cpp to the old version in which the addresses of the server were with www. in front

**Comment by squix78** [comment]
Hi guys

Thank you for this report. Could you please add some more information? Is this about WorldClockClient.cpp or TimeClient.cpp? Can you please add the output from the serial console and explain in more detail how you fixed it?

Thank you so much!

**Comment by marcelstoer** [comment]
> not returning time anymore

This (not mentioning any exceptions or the like) sounds suspiciously like #140 which I now fixed for `WorldClockClient.cpp` as well in dddb014f7f9bc14ca982099c1b73d1b4cf8ebc79.

**Comment by rverzinkevicius** [comment]
Hi,

for me issue is that time is not always received in wordclockdemo sketch. After several retries it succeeds.

**Comment by marcelstoer** [comment]
Works for me with the latest 1.6.4 -> closing
