### ISSUE TITLE
Library output is written to Serial instead of Serial1

### ISSUE THREAD

**Issue by Tiogaplanet** [ThingPulse/esp8266-weather-station#139]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Write library output to `Serial1` which is a dedicated debugging output port on the esp8266.

### Actual behavior
Library output is written to `Serial`.  If `Serial` or `Serial.swap()` is used for other devices, the library is writing to that other device.

### Test code
The following example comes from OpenWeatherMapCurrent.cpp.

```c
Serial.printf("Getting url: %s\n", url.c_str());
```
### Weather Station version
Which branch are you on? If you know the Git revision then add it here as well.

Master branch, as of commit [9407952](https://github.com/ThingPulse/esp8266-weather-station/commit/9407952ec25df95448ef77958becba899c32d8fe).

### Hardware
Describe whether you run the code on the ThingPulse Weather Station Color kit or on some custom hardware.

Using a Wemos D1 mini clone.

8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
Technically you're absolutely right. However, _not_ using `Serial` would be very unusual as pretty much all tutorials / documentation out there use it. Besides, the (hardware) projects this code targets, i.e. ours i.e. ThingPulse's, are not affected about this shortcoming. I personally don't see ourselves changing this.

@squix78 WDYT?

**Comment by Tiogaplanet** [comment]
Just to provide more detail, obviously the examples should output to `Serial`, but I think your library include files should not assume `Serial` is available for writing as it limits their usefulness in other projects.

For example, I'm using a Wemos D1 mini clone to [control the MiP robot](https://github.com/Tiogaplanet/MiP_ESP8266_Library).  I am using OpenWeatherMapCurrent.cpp and OpenWeatherMapCurrent.h to make the robot's eyes and chest indicate the weather and have the robot serve a web page with additional information.

For my implementation, I need the ESP8266 to read and write via `Serial` to the robot's UART.  If the library is writing to `Serial` then I'm sending a whole bunch of unusable data to the robot with potentially unpredictable results. 

I've lightly modified the OWM files to write to `Serial1` instead of `Serial` so that I can still read the output from the library includes but not clobber my robot with unusable data.  I'd like to suggest changing the library includes to either not generate output at all, provide an option for generating output (perhaps, `#define DEBUG 1` or similar) or writing to `Serial1` instead of `Serial`.

By the way, excellent library and thank you very much.  It's working great in my project.
