### ISSUE TITLE
Fix parsing OWM current data

### ISSUE THREAD

**Issue by marcelstoer** [ThingPulse/esp8266-weather-station#140]
Follow-up to https://support.thingpulse.com/799/currentweather-openweathermap-shows-espaper-everything

The proposed fix is to drop the outer loop at https://github.com/ThingPulse/esp8266-weather-station/blob/master/src/OpenWeatherMapCurrent.cpp#L68. The more I think about it the less I understand what the benefit actually is. Checking for available data should be enough.

**Comment by marcelstoer** [comment]
@G6EJD @SuperEugen see the enlightening feedback in the linked core issue.

**Comment by SuperEugen** [comment]
Good! Thanks that you clarified that with the WiFiClient developers!

**Comment by G6EJD** [comment]
Good to hear the core was changed and that the testing we did concluded the same.
So now coding techniques need to change to accommodate this.
I shall have to re-programme myself :)

**Comment by sorriso93** [comment]
It is not clear to me if now the library has been fixed.... many thanks

**Comment by marcelstoer** [comment]
We‘ll close this once it‘s fixed.

**Comment by G6EJD** [comment]
I think no fix is required and this is now the new behaviour, which is correct in TCP terms, previously it was incorrect.

**Comment by marcelstoer** [comment]
We have to adjust _this_ library.
