### ISSUE TITLE
Unable to compile TimeClient straight out of the box

### ISSUE THREAD

**Issue by cthompsonau** [ThingPulse/esp8266-weather-station#148]
Sample code doesn't compile for weatherstation. Returns the following error
```
C:\Users\christopher\Documents\Arduino\libraries\ESP8266_Weather_Station\src\TimeClient.cpp: In member function 'long int TimeClient::getCurrentEpochWithUtcOffset()':

C:\Users\christopher\Documents\Arduino\libraries\ESP8266_Weather_Station\src\TimeClient.cpp:124:67: error: invalid operands of types 'double' and 'long int' to binary 'operator%'

   return round(getCurrentEpoch() + 3600 * myUtcOffset + 86400L) % 86400L;](url)
```
We are using the default settings.h but something seems simple that we are missing. Any help would be appreciated.

```

#define UTC_OFFSET +1
struct dstRule StartRule = {"CEST", Last, Sun, Mar, 2, 3600}; // Central European Summer Time = UTC/GMT +2 hours
struct dstRule EndRule = {"CET", Last, Sun, Oct, 2, 0};       // Central European Time = UTC/GMT +1 hour
```

**Comment by wilhelmzeuschner** [comment]
I have the exact same issue and don't have any success trying to fix the error:

`return fmod(round(getCurrentEpoch() + 3600 * myUtcOffset + 86400L), 86400L); //Some UI elements flash at roughly 2-3Hz`

`int temp_value =  86400;
int temp_value_2 = round(getCurrentEpoch() + 3600 * myUtcOffset + 86400L);
return temp_value_2 % temp_value; //doesn't work either
`

**Comment by dmccuskey** [comment]
I had the same error – here was the modification i made which resulted in a successful compilation.

```
  return fmod(round(getCurrentEpoch() + 3600 * myUtcOffset + 86400L), 86400L);
```

Refs:
* https://stackoverflow.com/questions/9138790/cant-use-modulus-on-doubles
"The % operator is for integers. You're looking for the fmod() function"

**Comment by just-jason** [comment]
return fmod(round(getCurrentEpoch() + 3600 * myUtcOffset + 86400L), 86400L);
Works for me, thanks for the tip

**Comment by marcelstoer** [comment]
Not sure which application you compiled and in which environment you tried. I just tested WeatherStationDemoExtended and PlaneSpotterDemo (both use `TimeClient`) in Arduino IDE and both compile just fine straight out of the box.

**Comment by wilhelmzeuschner** [comment]
@marcelstoer I used the Arduino IDE v.1.8.5, the v.2.5.0 (beta2) ESP8266 board definition and selected the WEMOS D1 R2 board.

**Comment by just-jason** [comment]
I had issues when I tried to use the weather station demo, with the edited time client, it worked. I tried using IDE 1.8.3 & 1.8.7 both threw the same errors

**Comment by plazmax** [comment]
Downgrade esp8266 2.5.x beta to 2.4.x stable itll be solved.

**Comment by marcelstoer** [comment]
> ...the v.2.5.0 (beta2)

We've had issues with that before, sigh. While it's true that floating point division does not have a
remainder, hence `fmod`, it's unfortunate that the ESP8266 Arduino-core team is pushing their betas onto the official release channel.
