### ISSUE TITLE
WeatherStationDemo doesn't correctly set 12H time

### ISSUE THREAD

**Issue by webdevbrian** [ThingPulse/esp8266-weather-station#150]
### Expected behavior

That `uint8_t allowedHours[] = {12};` is declaring 12H time format, so that when a user changes the utc TZ timezone, it correctly sets the offset

### Actual behavior

`uint8_t allowedHours[] = {12};` and using `uint8_t allowedHours[] = {24};` both use 24H time format

### Test code
```c
  uint8_t allowedHours[] = {12};
  forecastClient.setAllowedHours(allowedHours, sizeof(allowedHours));
```

### Weather Station version
v1.6.5

### Hardware
NodeMCU V1 using a 4 pin 128x64 OLED

**Comment by marcelstoer** [comment]
Sorry we missed this. You're misinterpreting what `allowedHours` does and unfortunately it's not documented. See https://github.com/ThingPulse/esp8266-weather-station/issues/145#issuecomment-481277542 for an explanation of that setting.

The 12/24H style flag that some of our applications support isn't built into that demo. See 

https://github.com/ThingPulse/esp8266-weather-station-color/blob/0119e4938ea7c61a3eb316506e9b8c5bdab06163/esp8266-weather-station-color.ino#L358-L374

for an inspiration for how you would need to change your code.
