### ISSUE TITLE
The Weather Underground API has reached the end of service

### ISSUE THREAD

**Issue by sabretus** [ThingPulse/esp8266-weather-station#154]
My weather station just stopped working and this is what I've found on WU site:

> Attention: The Weather Underground API has reached the end of service. To purchase access to the replacement API, please see our Weather Data Packages. If you are a contracted, paying customer and feel you have been shut off in error, please email feedback.wunderground@weather.com; be sure to include your name and API key.

Original link https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api

They are also offering APIs for PWS https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit

**Comment by marcelstoer** [comment]
We migrated away from WU in May 2018 when they stopped giving out new free API keys, see https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/ for details.

**Comment by sabretus** [comment]
@marcelstoer 
I'm sorry, but what about WeatherStationDemoExtended and WeatherStationDemoExtendedDST examples? Are you going to update them with openweathermaps libraries? 

Thanks!

**Comment by marcelstoer** [comment]
All code in this library that still depends on WU [will be removed in June 2019](https://github.com/ThingPulse/esp8266-weather-station#deprecation-notes). So, it's unlikely we'll update the examples that have not been migrated so far until then.
