### ISSUE TITLE
OpenweatherMapForecastDemo - Needing all 6 daily reports

### ISSUE THREAD

**Issue by bill-orange** [ThingPulse/esp8266-weather-station#156]
I got the OpenweatherMapForecastDemo running on my ESP32 with little difficulty.  The data appears to be collected from:

`http://api.openweathermap.org/data/2.5/forecast?id=`

I believe that this URL will provide a maximum of 6 timestamped reports for each day.  Does the demo restrict this maximum somehow?  I see only two reports per day.  Allowed hours might have something to do with it but changing:

`client.setAllowedHours(allowedHours, 4);`

from 2 to 4 or 6 has no effect.

**What am I missing? Could there be a bug in allowed hours?** 

Changing  MAX_FORECASTS also has no effect.

What I am really after is the next two forecasts after the present local time.

**Comment by bill-orange** [comment]
Okay I think that I answered my own question.  First, I need only two reports, so set `MAX_FORECASTS = 2`

AllowedHours means just what the name implies.  For all 24 hours set allowed hours to:

`uint8_t allowedHours[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};`

I want this to work all day so set `client.setAllowedHours(allowedHours, 24);`

There is one modification to the cpp file needed.  'Hourly' needs to be added to the URL:
line 45:
` return "http://api.openweathermap.org/data/2.5/forecast/hourly?" + locationParameter + "&appid=" + appId + "&units=" + units + "&lang=" + language;

So far I am getting what I need, the next two hourly forecasts.
`

**Comment by marcelstoer** [comment]
Glad it works for you as expected now. The reason the hourly forecasts are not part of the library is because the OWM API for those is not free. As per https://openweathermap.org/price it's just a _free trial_. Should they decide to make it available in the free tier we are definitely interested in offering support for it.

**Comment by bill-orange** [comment]
Wow!  I am glad you pointed that out before I wrote a whole lot of code around the hourly forecasts. 

One other question. As a data integrity check, I would like to parse the ‘cod’ field. I don’t expect you to write the code for me, but what changes would I need to make to the .h and .cpp file?  ‘Cod’ is not part of the weather array. That’s what confuses me.

**Comment by marcelstoer** [comment]
`cod`? You mean `code`, right?

Look at https://github.com/ThingPulse/esp8266-weather-station/blob/master/src/OpenWeatherMapForecast.cpp#L107 and something like this

```c++
if (currentKey == "code") {
  data[currentForecast].code = value.toInt();
}
```

**Comment by bill-orange** [comment]
Nope.  I mean 'cod'  It is the first Item under object at the same level as list.  Therein lies the problem.  It is not part of the array with the other data.
