### ISSUE TITLE
No matching function for call to 'BLEserial::BLEserial(int, int, int)' [HELP] (Blynk APP) (Arduino)

### ISSUE THREAD

**Issue by tdjelley** [ThingPulse/esp8266-weather-station#159]
8<------------------------ BUG REPORT -----------------------------------------

/* Comment this out to disable prints and save space */
#define BLYNK_PRINT Serial

#include <Adafruit_ATParser.h>
#include <Adafruit_BLE.h>
#include <Adafruit_BLEBattery.h>
#include <Adafruit_BLEEddystone.h>
#include <Adafruit_BLEGatt.h>
#include <Adafruit_BLEMIDI.h>
#include <Adafruit_BluefruitLE_SPI.h>
#include <Adafruit_BluefruitLE_UART.h>

#include <BlynkSimpleSerialBLE.h>
#include <BLEPeripheral.h>
#include "BLESerial.h"
#include <SPI.h>
#include <Servo.h>

Servo tomservo; // servo name

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "AuthTokenHere";

int bluetoothTx = 10; // bluetooth tx to pin 10
int bluetoothRx = 11; // bluetooth rx to pin 11

// define pins (varies per shield/board)
#define BLE_REQ   10
#define BLE_RDY   2
#define BLE_RST   9

// create ble serial instance, see pinouts above
BLESerial SerialBLE(BLE_REQ, BLE_RDY, BLE_RST);

Servo servo;

BLYNK_WRITE(V3)
{
  servo.write(param.asInt());
}

void setup()
{
  // Debug console
  Serial.begin(9600);

  SerialBLE.setLocalName("Blynk");
  SerialBLE.setDeviceName("Blynk");
  SerialBLE.setAppearance(0x0080);
  SerialBLE.begin();

  Blynk.begin(SerialBLE, auth);

  Serial.println("Waiting for connections...");

  servo.attach(7);
}

void loop()
{
  SerialBLE.poll();
  Blynk.run();
}

**Comment by tdjelley** [comment]
I have installed all of the required libraries on Arduino for SerialBLE etc.

**Comment by tdjelley** [comment]
I am also using the Adafruit Bluefruit LE UART Friend.

**Comment by marcelstoer** [comment]
This is not a general Arduino issues list. There are established forums for that -> closing
