### ISSUE TITLE
Constantly Restarting

### ISSUE THREAD

**Issue by shortsguy** [ThingPulse/esp8266-weather-station#162]
I have the stock code, stock pieces and haven't changed anything. I updated the firmware, uploaded the code, wired as diagram and it just keeps restarting. I have a 2.0A battery pack, regular usb into laptop, and a smart phone charger and they all have the same result. Constantly restarting.

Only thing I know that may be a sign is that the time is always wrong.

any help is greatly appreciated.

**Comment by marcelstoer** [comment]
We prefer to route customer support requests to https://support.thingpulse.com/ rather than addressing them on the issues list.

The serial console is likely to reveal relevant information. Please make that available.

**Comment by shortsguy** [comment]
I do not mean to sound dumb. I am on linux, how do I provide serial console?

**Comment by marcelstoer** [comment]
I'm going to close this as it's unrelated to our hardware and to the software in this repository. You would open the serial console in the Arduino IDE through Tools -> Serial Monitor. However, the stacktrace indicates you're likely not getting this far.

My guess is that you're running an Arduino IDE version (or a component thereof) that requires Java 9 but your system has Java 8 installed. On 8 `ByteBuffer.flip()` returns `java.nio.Buffer` but in your case some code is looking for a `flip()` that returns `java.nio.ByteBuffer` - and that is the signature found in 9 onwards.
