### ISSUE TITLE
New version of the ESP8266 Weather Station TFT Display

### ISSUE THREAD

**Issue by Dancopy** [ThingPulse/esp8266-weather-station#163]

**Comment by Dancopy** [comment]
Is there a New Version of ESP8266 Weather Station for TFT Display (ILI9341)?
Wunderground no longer provides free APIs. Thanks

**Comment by marcelstoer** [comment]
https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/ should answer this. The current version doesn't use Wunderground anymore.
