### ISSUE TITLE
HTTPS weather API

### ISSUE THREAD

**Issue by CorentinMaisonneuve** [ThingPulse/esp8266-weather-station#166]
I'm trying to create a library for the DarkSky API in keeping with the spirit of the other weather API libraries.
I'm stuck on the fact that DarkSky only allows https though. And not being a skilled programmer, I am struggling to try and adapt these kinds of examples: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino as they are using the WifiClientSecure in a different way the HTTPClient is used in your project (no begin method with WifiClientSecure, no creation of a WifiClient from the HTTPClient getStreamPtr).
I'm sure this wouldn't be much of an issue for someone experienced, but I'm a bit lost here.

**Comment by marcelstoer** [comment]
There is so much to say about TLS/SSL, sigh.

Use BearSSL as it's the new default library in ESP8266 Arduino core.

I suggest you take a look at https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/bearssl-client-secure-class.html for starters. The BearSSL example sketch is at https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino. 

Managing certificates and truststores can be a real pain on IoT devices. Even more so when your code is a library and you don't want to impose that on the library users. Currently both Aeris and OpenWeatherMap still support plain HTTP APIs. For the time being we, therefore, get away with ignoring the TLS questions - at least for the library. There are other projects where we use encrypted connections.

Side note: Aeris and DarkSky use certificates signed by Amazon Root CA 1 while OpenWeatherMap uses the COMODO RSA CA -> this library can support all three APIs and use the same CA certificate

**Comment by CorentinMaisonneuve** [comment]
Thank you so much for taking the time to answer.
Reading a bit on the BearSSL doc, I can see why you wouldn't add encrypted connections to a library, on top of the certificate management, there are a lot of questions around cpu and memory requirements. I'll give a try to BearSSL, as I'd be happy to do an insecure request to an HTTPS endpoint. If it still doesn't work I'll be better following your wisdom and ignoring the TLS question myself, I'll just have to pivot a bit on what I had in mind for my project.

**Comment by sungkhum** [comment]
@CorentinMaisonneuve Did you ever succeed in creating a link with the DarkSky API?
