### ISSUE TITLE
temp_min & temp_max are wrong

### ISSUE THREAD

**Issue by saddys** [ThingPulse/esp8266-weather-station#168]
The temp_min and temp_max responde with average temp and no with min & max temp.

In src/OpenWeatherMapForecast.cpp are correctly called (temp_min and temp_max). There is a solution?

If I call from browser, I get all ok:

{"coord":{"lon":10.95,"lat":45.89},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"base":"stations","main":{"temp":299.61,"pressure":1015,"humidity":44,"temp_min":295.37,"temp_max":302.15},"visibility":10000,"wind":{"speed":2.1,"deg":200},"clouds":{"all":0},"dt":1567611132,"sys":{"type":1,"id":6776,"message":0.0074,"country":"IT","sunrise":1567572022,"sunset":1567619450},"timezone":7200,"id":6534633,"name":"Ronzo-Chienis","cod":200}

Thanks

**Comment by marcelstoer** [comment]
I don't understand what the problem is. Please describe in more detail or with more references.

**Comment by saddys** [comment]
The problem is that if I Serial.print(tempMin) and Serial.print(tempMax), the output is the same temperature of "temp" api (in my case, 229.61) and no 295.37 and 302.15.

**Comment by saddys** [comment]
Sorry, i mismatch current with forecast url string, and the min and max temp are the same (at 12.00pm o'clock unix) in api too.

**Comment by marcelstoer** [comment]
It's the limitation of their API. Please consider https://openweathermap.org/forecast5#min. If you use the 5 day / 3 hour forecast API you need to calculate the daily min/max yourself based on the `temp` for each of the 8 values per day.
