### ISSUE TITLE
API_Keys of thingspeak.com

### ISSUE THREAD

**Issue by Next9999** [ThingPulse/esp8266-weather-station#184]
Use one of the two templates below and **delete the rest**.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
in the example of the weatherstatiodemo the feature API_Keys of thingspeak.com is not there

### Actual behavior
No API_Keys of thingspeak.com in the example
```
Add serial console output here
```

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

```c
// add code here
```
### Weather Station version
Which branch are you on? If you know the Git revision then add it here as well.

### Hardware
Describe whether you run the code on the ThingPulse Weather Station Color kit or on some custom hardware.

8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
You have to get your own by creating an account there.
