### ISSUE TITLE
ESP32 again

### ISSUE THREAD

**Issue by millenseer** [ThingPulse/esp8266-weather-station#186]
### Expected behavior
should compile

### Actual behavior
Compiling "WeatherStationDemo.ino"

```
C:\Arduino\libraries\ESP8266_Weather_Station\src\AerisForecasts.cpp: In member function 'void AerisForecasts::doUpdate(AerisForecastData*, String, uint8_t)':
C:\Arduino\libraries\ESP8266_Weather_Station\src\AerisForecasts.cpp:48:31: error: no matching function for call to 'WiFiClient::connect(const String&, const uint8_t&)'
   if(client.connect(host, port)) {
                               ^
```

What am I missing? 

I added this code to AerisObservations.cpp and AerisForecasts.cpp
```
typedef signed short        sint16_t;
typedef signed long         sint32_t;
```

Those Aeris-Files are not required for the standard Demo "WeatherStationDemo.ino". The "WiFiClient::connect"-error remains even after removing them.

Arduino-Version 1.8.13, latest and updated libraries and boards.
Any help please? 

### Weather Station version
master

### Hardware
D-Stike 32

**Comment by jowiemann** [comment]
Hello,

replace in OpenWeatherMapForecast.cpp, OpenWeatherMapCurrent.cpp, AerisObservations.cpp, AerisForecasts.cpp and AerisSunMoon.cpp the line 

if(client.connect(host, port)) {

with

#if defined(ESP8266)
  if(client.connect(host, port)) {
#else
  if(client.connect(host.c_str(), port)) {
#endif

Greetings Jörg

**Comment by marcelstoer** [comment]
There's preliminary support for ESP32 in a dedicated branch: https://github.com/ThingPulse/esp8266-weather-station/compare/esp32

- everything compiles in CI
- none of the examples have actually been tested on hardware yet
