### ISSUE TITLE
PlatformIO.ini comma in Libdeps not accepted and compliation errors

### ISSUE THREAD

**Issue by wimmatthijs** [ThingPulse/esp8266-weather-station#189]
### Expected behavior
compliation succcessful

### Actual behavior
failed imports for platformio due to the extra comma behind JsonStreamingParser
remove comma from platformio.ini pls

another issue is the WiFiManager library expects includes of <ESP8266WiFi.h>, <ESP8266WebServer.h> and <DNSServer.h>
in the main.cpp program however this is not included in the examples

**Comment by marcelstoer** [comment]
Kinda fixed with 2ce4985bfc9081cc336515d67d16bdabc12fb75e
