### ISSUE TITLE
missing wunderground graphics 

### ISSUE THREAD

**Issue by prussiap** [ThingPulse/esp8266-weather-station#19]
Hi,
Trying to do something similar for V-day present.. stumbled on your project to speed things along :) . Thanks for the great work btw.
I'm planning on using a DHT22 attached directly and using ip location to get zip or country automatically. I don't mind uploading after if it helps you.
I'm attaching a video of what I have and have a few things that don't seem to work.
video (sorry dark): https://www.dropbox.com/s/75ltowtzgdfr1e2/2016-02-11%2021.37.54.mov?dl=0
- Frame 1: is blank right now. With UTC 5 i'm off by 3hrs and am on east cost of US. Normal UTC time breaks reading.
- Frame 2: Seems to be get temp from wunderground, hard coded for oC (shows NA for me). Also this seems to get a weather icon? wunderground.getTodayIcon(); There is an array of weather name to letter in the WeatherUnderground.cpp but I can't seem to find any bmp or array version corresponding to each of the icons (a..k... on ). I'm not getting any graphics drawn but that could be that i'm missing a file or some arrays?
- Frame 3: probably same reason for the rest not getting temp/humidity/weather.
- Frame 4: actually this might be drawing graphics.. though nothing more then "/ / /" on it.
- Frame 5 is always C no matter what I set for isMetric (will check in the am) It's probably showing your c or some defaults and I'll change this to DHT22 .. 

Sorry to bug for some of this but I have put my Wunderground Keys. and copied the exact country city values from : http://api.wunderground.com/api/mykey/conditions/q/zip.json

Planning to use this to get the zip from ip, then add zip value to get weather but I'd like to understand what's wrong before breaking anything new ...

Thanks,

**Comment by marcelstoer** [comment]
Spring clean-up of old and stalled issues, feel free to reopen.
