### ISSUE TITLE
Hello i‘m trying to change the time between changing frames, but I could not find code where to change. May someone could help ? Thank in advance , greetings Tomster

### ISSUE THREAD

**Issue by Tomster99** [ThingPulse/esp8266-weather-station#191]
Use one of the two templates below and **delete the rest**.

8<------------------------ BUG REPORT -----------------------------------------
### Actual behavior

```
Add serial console output here
```

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

```c
// add code here
```
### Weather Station version
Which branch are you on? If you know the Git revision then add it here as well.

### Hardware
Describe whether you run the code on the ThingPulse Weather Station Color kit or on some custom hardware.

8<------------------------ END BUG REPORT -------------------------------------

8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
Tell us why you would like to see this feature added.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by IldeNet** [comment]
+1 I would like to keep the time frame longer, but I can't find the variable.

**Comment by renatobo** [comment]
Have you tried using
```
   void setTimePerFrame(uint16_t time);
```
from the [OledDisplayUI](https://github.com/ThingPulse/esp8266-oled-ssd1306/blob/master/src/OLEDDisplayUi.h) library on the `ui` variable?

**Comment by IldeNet** [comment]
> Have you tried using
> 
> ```
>    void setTimePerFrame(uint16_t time);
> ```
> 
> from the [OledDisplayUI](https://github.com/ThingPulse/esp8266-oled-ssd1306/blob/master/src/OLEDDisplayUi.h) library on the `ui` variable?

Thank you very much for the help, adding in line 166 "ui.setTimePerFrame (6000);" I was able to double the time per frame.
Thanks for your time

**Comment by marcelstoer** [comment]
@renatobo thanks for the answer, I didn't initially understand what this was all about but you were spot-on.

> line 166 "ui.setTimePerFrame (6000);"

Ok, I get it. This obviously refers to one of the sample sketches (WeatherStation, WorldClock, or PlaneSpotter).
