### ISSUE TITLE
New sketch for OWM onecall does IOT and forecast

### ISSUE THREAD

**Issue by TerryLaP** [ThingPulse/esp8266-weather-station#194]
8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
I think it makes sense this way.  I purchased the ideaSpark WeatherStation kit.

### Workarounds
I have never posted code to github.  Not sure if anyone wants my code example, but I'm willing to share it.  But I don't have any idea about how to go about sharing it.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
https://github.com/ThingPulse/esp8266-weather-station/blob/master/examples/OpenWeatherMapOneCallDemo/OpenWeatherMapOneCallDemo.ino

This was released on 2021-11-18 with 2.1.0.
