### ISSUE TITLE
Local / Room temperature 

### ISSUE THREAD

**Issue by Mostum** [ThingPulse/esp8266-weather-station#197]
------------------------ FEATURE REQUEST ------------------------------------
### Justification
I saw it was once possible to connect a DHT sensor to show the local temperatur. I dont know why it was deleted or if you are planning on bringing it back.
But it be a neat feature, even without logging the data at all.
------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
The starter kit tutorial covers this well: https://docs.thingpulse.com/guides/iot-starter-kit/

**Comment by Mostum** [comment]
Yea, i´ve seen this one before.

But i could not find the part stated on page 54:
```
Look for these lines in the demo and replace the read api key and the channel ID with the ones you
got in the Thingspeak step:

//Thingspeak Settings
2 const String THINGSPEAK_CHANNEL_ID = "67284";
3 const String THINGSPEAK_API_READ_KEY = "L2VIW20QVNZJBLAK";
```

in the WeatherStationDemo of version 2.0.1

**Comment by Mostum** [comment]
Is the documentation even up to date, as it is from 2018-09-11..
