### ISSUE TITLE
Polish characters

### ISSUE THREAD

**Issue by EDIIP** [ThingPulse/esp8266-weather-station#201]
Hi, first of all I would like to congratulate you on an interesting project, I have just made an ESP8266 board on it, but after setting the Polish language, unfortunately the Polish characters Ą Ś Ł Ż Ź Ć Ń Ę Ó and ą ś ł ż ź ć ń ę ł ó are not displayed. Is there a chance to add these characters, I will be very grateful for this, and certainly other users from Poland.

**Comment by marcelstoer** [comment]
Across our various repositories similar requests were voiced a couple of times. Examples: https://github.com/ThingPulse/esp8266-oled-ssd1306/issues/343, https://github.com/ThingPulse/esp8266-weather-station-color/issues/61

-> you need to adjust the font file manually
