### ISSUE TITLE
Not an issue, ESP8266 wth ST7789

### ISSUE THREAD

**Issue by abdelhadj** [ThingPulse/esp8266-weather-station#202]
Hello,

Thank you for your code! works great.
do you think it is complex to adapt it to ST7789?
Thank you!

**Comment by marcelstoer** [comment]
> do you think it is complex to adapt it to ST7789

I don't think so. That gorgeous display works over SPI and the Adafruit GFX library is mature and supports ESP8266. You will just have to replace all `display.someFunction()` calls with their GFX equivalent in the sketch.

**Comment by abdelhadj** [comment]
Sorry,
just to be more specific, what would be the equivalent library to the one ou are using SSD1306Wire?

SSD1306Wire     display(I2C_DISPLAY_ADDRESS, SDA_PIN, SDC_PIN);
