### ISSUE TITLE
instructions how to install ESPHTTPClient.h are missing

### ISSUE THREAD

**Issue by StefanL38** [ThingPulse/esp8266-weather-station#206]
I appreciate that you provide source-code opensource of course.

anyway: I recommend if you publish any kind of project to github to **really**  do 
all the steps that you describe in the documentation from the same start-position as a newbee.

This means use a computer that has **ZERO** arduino installation
And do **ALL** the steps from there.

By testing your documentation this way you would have found that your documentation is MISSING the installation of file **ESPHTTPClient.h**

![image](https://user-images.githubusercontent.com/8948220/197327726-209e747d-21bc-4f1b-bab5-9a3b6797206f.png)

best regards Stefan

**Comment by marcelstoer** [comment]
The README is correct. `ESPHTTPClient.h` is part of this very library: https://github.com/ThingPulse/esp8266-weather-station/blob/master/src/ESPHTTPClient.h. Also, the [library ZIP](https://www.arduinolibraries.info/libraries/esp8266-weather-station) that Arduino installs does contain this header file.
