### ISSUE TITLE
TimeClient.updateTime() failing

### ISSUE THREAD

**Issue by hwiguna** [ThingPulse/esp8266-weather-station#22]
Dani, thank you for sharing your awesome weather station!
I built it yesterday and it was working great. Today it stopped working.  :-(
I pinpointed it down to TimeClient.updateTime() failing.

As you know, updateTime() GETs www.google.com and parse out the DATE.
For some reason, Google is sending TONs of stuff overloading the poor ESP8266.  I saw crash report on the serial.

I was able to solve it by adding User-Agent: Lynx (textmode) to the GET header (just after Host: www.google.com).  Google sends bare minimum HTML that made the ESP much happier.
All is well again. :-)

**Comment by jhapke** [comment]
Thanks hwiguna, 
   My NodeMCU 1.0 ESP-12E was rebooting continuously. With "FATAL EXCEPTION (28)"

It now appears to be fixed. 

Detailed Changes:
TimeClient.cpp

     41   client.print(String("GET / HTTP/1.1\r\n") +
     42                String("Host: www.google.com\r\n") +
     43                String("User-Agent: Lynx (textmode)\r\n") +
     44                String("Connection: close\r\n\r\n"));

**Comment by marcelstoer** [comment]
> I was able to solve it by adding User-Agent: Lynx (textmode) to the GET header

Apart from the fact that this doesn't seem to work anymore (Google still sends you 11KB of data) it is a fragile strategy. As we're just interested in a `Date` header from a known and reliable source relying on that source doing content negotiation on the user agent isn't the most reliable. 

You want to send a request that yields the smallest possible response. You could opt for HTTP 404 but some sites return some really fancy not-found pages. 
--> go for HTTP 301, those responses contain absolutely minimal body - if at all

Fixed it in 1524e03.
