### ISSUE TITLE
Cannot flip screen (solved)

### ISSUE THREAD

**Issue by bHogan2** [ThingPulse/esp8266-weather-station#23]
display.flipScreenVertically() only affects the first screen ("Connecting to WiFi").
After that the screen is not flipped anymore.

**Solved by also adding display.flipScreenVertically() in drawProgress() as well.**

I'm also wondering if there is a bold version of the included Arial font used. Or what would be the name of that font in your font generator page.

Terrific work. Thanks, John

**Comment by Thomas1305** [comment]
Display still don´t flip? (uncomment  display.flipScreenVertically();)
What else can i do?

**Comment by ackbad** [comment]
> Display still don´t flip? (uncomment display.flipScreenVertically();)
> What else can i do?

Did you ever figure this out?

**Comment by alexandru-2016** [comment]
In the WeatherStationDemo
add display->flipScreenVertically(); at the end of drawProgress
