### ISSUE TITLE
TimeClient did not pick up change to Daylight saving / summertime

### ISSUE THREAD

**Issue by dennisvane** [ThingPulse/esp8266-weather-station#24]
Hi all,

I'm using the Weatherstation that Dani made.
At 27th of march Daylight Saving Time started and since then the weather station shows 1 hour too early. I looked if I could resolve this but I could not and actually I dont understand why it fails. Because the time and date come from google right? So shouldn't that be uptodate?

Best regards
Dennis van Elteren

**Comment by squix78** [comment]
Hi Dennis
I also discovered this bug but didn't have time to fix it yet. A temporary fix (until the time is switched back to "normal"/winter time is that you adjust the UTC_OFFSET flag and increase it by one. Google sends the time in UTC and this is not affected by day light saving at all. Let me know if the temporary work around helped...

**Comment by dennisvane** [comment]
Hi Dani

Tnx for that! I was thinking about cheating that way. I hope you find time
in the future to fix it or that I figure out how to (not likely).

Are you not working on your blog anymore?

Cheers,
Dennis

2016-04-10 13:20 GMT+02:00 squix78 <notifications@github.com>:

**Comment by dennisvane** [comment]
I can confirm UTC_OFFSET  setting to 2 helps, tnx!

**Comment by Olivier-11** [comment]
Hi Dani,
Thank you for this very good job
About Daylight saving i struggled and found a piece of code in the Arduino forum from Jeroen
int adjustDstEurope()
{
 // last sunday of march
 int beginDSTDate=  (31 - (5* year() /4 + 4) % 7);
 Serial.println(beginDSTDate);
 int beginDSTMonth=3;
 //last sunday of october
 int endDSTDate= (31 - (5 * year() /4 + 1) % 7);
 Serial.println(endDSTDate);
 int endDSTMonth=10;
 // DST is valid as:
 if (((month() > beginDSTMonth) && (month() < endDSTMonth))
     || ((month() == beginDSTMonth) && (day() >= beginDSTDate))
     || ((month() == endDSTMonth) && (day() <= endDSTDate)))
 return 7200;  // DST europe = utc +2 hour
 else return 3600; // nonDST europe = utc +1 hour
}

I made the update in TimeCleint.h and TimeClient.cpp
As i am not a programmer this is a quick and dirty patch but it works

[ESP8266_Weather_Station_time_dst.zip](https://github.com/squix78/esp8266-weather-station/files/217577/ESP8266_Weather_Station_time_dst.zip)

Best regards Olivier

**Comment by totof60** [comment]
Thanks Olivier-11

it works for me

**Comment by k5map** [comment]
Following up to see if this issue has been resolved without having to manually change UTC_OFFSET

**Comment by dennisvane** [comment]
No not that I know!

2016-12-12 23:27 GMT+01:00 Mike <notifications@github.com>:

**Comment by edfcastro** [comment]
Just sharing how I managed to solve this issue for my case.
In my country DST definition is a mess! Start and end date are not allways the same. And as it is a continental size country, some states are in DST and others are not. So there is no way to make it automatic. I modifed The **TimeClient.cpp** library and add a small switch  to the port 4 connecting it to GND or Vcc. When it is connected to GND it adds 1 to utcoffset on startup. It is far from a beautifull solution, but is better then editing and downloanding twice a Year. This is the modification (**TimeClient.cpp**):

Before:

```
TimeClient::TimeClient(float utcOffset) { 
myUtcOffset = utcOffset;
}
```



After:

```
TimeClient::TimeClient(float utcOffset) {
  if (digitalRead (4) == HIGH) {myUtcOffset = utcOffset; }
  else {myUtcOffset = utcOffset+1; }
}
```

Don´t forget to set port 4 as input in main program (  _pinMode(4, INPUT_PULLUP);_ ) and, offcourse, add a small lockable switch between GND and port 4.

**Comment by dennisvane** [comment]
clever workaround!

**Comment by dennisvane** [comment]
Hey all I just figured out a simple workaround!

Instead of getting the Google server time I now use the Wunderground client time since I use a local station the time is correct. Just locate the function drawFrame1 and change here 1 line, the one where string time gets the time assigned:

`bool drawFrame1(SSD1306 *display, SSD1306UiState* state, int x, int y) {
  display->setTextAlignment(TEXT_ALIGN_CENTER);
  display->setFont(ArialMT_Plain_10);
  String date = wunderground.getDate();
  int textWidth = display->getStringWidth(date);
  display->drawString(64 + x, 10 + y, date);
  display->setFont(ArialMT_Plain_24);
  /**********DVEdebug trying to solve the UTC offset problem by getting the time from the wunderground client******/
  //String time = timeClient.getFormattedTime(); //this gets the time from the Google server and here I have the UTC offset problem
  String time = wunderground.getHours() + ":" + wunderground.getMinutes() + ":" + wunderground.getSeconds(); //here I get the time from the local Wunderground station, problem solved
  /**********END DVEdebug trying to solve the UTC offset problem by getting the time from the wunderground client******/
  textWidth = display->getStringWidth(time);
  display->drawString(64 + x, 20 + y, time);
  display->setTextAlignment(TEXT_ALIGN_LEFT);
}`
