### ISSUE TITLE
Time (seconds in frame1) standing still and only get updated when frame changes 

### ISSUE THREAD

**Issue by ht81** [ThingPulse/esp8266-weather-station#26]
Hello Daniel,

first thanks for this amazing project! I have found a bug: i´ve installed all librarys etc. as you discriped in your post. All works fine, but the time in frame1 is not ticking sec. by sec. it shows xx seconds an for the frame time (5s) nothing happends. The time (seconds) ist standing still.  But when the frame changes to frame2 the time is updating and shows the actuall seconds to the time. 

i have arduino 1.6.5, with nodeMCU v1.0 and the ssd1306 display.

Any idea? How can i debug this issue?

I already open a ticket on github for this issues.

Thanks and greetigs

Thomas

**Comment by RogerSchaefer** [comment]
Hello Thomas,

In your oled setup add the line:
ui.setTargetFPS(30);

That should fix it.
Oldmicroguy

**Comment by stony2k** [comment]
Same issue here, ui.setTargetFPS(30); was already added. I remember that the ticking seconds worked in the past. Roger, does it work for you?

**Comment by RogerSchaefer** [comment]
Hi,

Yes it does work for me.
The blue LED on the NodeMCU is on continuously while the time frame is displayed indicating the the data for the frame is being continuously updated.
With the other frames the LED is only on briefly.

That said, before I sent this email I retested by commenting out that line and it made no difference.  So I am getting the ticking seconds but don’t know why.

If you send me your email I’ll send you a copy of my version.
Roger

**Comment by stony2k** [comment]
Could post your code here so everyone could benefit from it? :)

**Comment by RogerSchaefer** [comment]
Well, not at this time.
It’s really Daniel Eichhorn program.
And I am not finished with the modifications I wanted to make.  Hopefully Daniel will find a solution to the 512 byte limit so weather alerts can be loaded.
Roger

**Comment by ht81** [comment]
Hi Daniel,

i have found a solution that work for me but i dont know what is going false here. In the function "bool drawFrame1"  i have to add "return true;" at the end. Then it works correctly. But why? Is this a really a bug? I work with your latest Code showing up in Arduino IDE

**Comment by RogerSchaefer** [comment]
Hello ht81,

I just tried adding “return true” and it didn’t help.

Thankfully, most places, most times do not have severe weather and the “alerts” function returns very little.  However, if you plug in a location that is currently experiencing severe weather “alerts” will return a field called “message” which is very long.  Whenever the program encounters a field with more than 512 bytes it crashes.   That is the problem.

Roger

**Comment by ht81** [comment]
Hi Roger,
ok i understand. Is it possible to disable the alerts in wounderground? Or have Daniel to bugfix this? Can you tell me why my Solutions also work?

**Comment by stony2k** [comment]
Just updated this lib and made the new changes in comparison to the weather station demo: ticking seconds work without adding a "return true;" in "void drawDateTime" (old "bool drawFrame1")

**Comment by ht81** [comment]
stony2k confirmed. This works now :)
