### ISSUE TITLE
Is it possible to change the delay between frame changes

### ISSUE THREAD

**Issue by aliceand** [ThingPulse/esp8266-weather-station#38]
This is probably obvious, but I wanted to change the delay between frame changes (make each frame display longer before moving to next).  Is that possible?

**Comment by neptune2** [comment]
Yes, See line 162 of the new [examples/WeatherStationDemoExtendedDST/WeatherStationDemoExtendedDST.ino](https://github.com/squix78/esp8266-weather-station/blob/master/examples/WeatherStationDemoExtendedDST/WeatherStationDemoExtendedDST.ino#L162)

`ui.setTimePerFrame(10*1000); // Setup frame display time to 10 sec`

This can be added to any of the examples with multiple screens.

-Neptune
