### ISSUE TITLE
wunderground API usage alert

### ISSUE THREAD

**Issue by aliceand** [ThingPulse/esp8266-weather-station#40]
I was just chastised by wunderground for high API usage.

I've been loading and rebooting the weather station app a lot today which might account for my high usage, but it got me to thinking .... will running the app 24 hours a days stay within the wunderground allocation of API calls for free accounts, or are we pushing the limit?

**Comment by antonioag95** [comment]
I'm just wondering the same. How many requests to Wunderground are done every time it updates its values? I'm not an expert, but looking at the code seems that multiple requests are made at once. Can please @squix78 answer to this question?

**Comment by pypingou** [comment]
Depending on which code you're running but the default in https://github.com/squix78/esp8266-weather-station/blob/master/examples/WeatherStationDemo/WeatherStationDemo.ino#L50 is to update every 10 minutes, so that's 6 updates / hour and 144 updates / day which is way under the limit for free API keys (500 requests / day and max 10 requests / minute)

**Comment by squix78** [comment]
The code does indeed several calls during update: conditions, forecasts, astronomy, alerts. Every call counts towards the daily limit so with 4 calls per update and updates every 10 minutes brings you to 576 calls per day. Reducing the update frequency to 15 minutes would solve this problem...

**Comment by aliceand** [comment]
It's been awhile, but I remember combining all updates into one call to lower my wu hit count.  Seemed like a big win since I could lower the update frequency and have fresher data.  The wu side was easy, just combine calls e.g. conditions/forecast/astronomy/alerts/.  The station code involved more, but it was still only a few lines of code change.

**Comment by erkobg** [comment]
You can chain together multiple requests in the same call, and it will count as only one call . Here's an example: 
http://api.wunderground.com/api/____YOUR_KEY____/**forecast**/**astronomy**/**conditions**/q/CA/San_Francisco.json

Might help https://apicommunity.wunderground.com/weatherapi/topics/combine_api_calls

**Comment by squix78** [comment]
I know about that but I recently separated all the parsers into different classes so users could use resources (mostly heap memory) more efficiently. So while you can do chaining with the deprecated all-in-one class it will not help much with the new ones unless you store the json file on flash and run it through all the parsers. That however might be bad for flash wear-out. So I came to the conclusion that reducing update frequency the lesser of two evils. Happy to revoke my judgment if I'm missing something here...

**Comment by marcelstoer** [comment]
[Weather Underground closed their existing API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api) for non-paying customers on 2018-12-31. After [they stopped issuing free API keys](https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/) for low-volume personal use in May we migrated to OpenWeatherMap and [deprecated all WU code](https://github.com/ThingPulse/esp8266-weather-station#deprecation-notes) in this library.

We are now closing all WU-related issues and PRs.
