### ISSUE TITLE
dht22 example

### ISSUE THREAD

**Issue by patricklaidlaw** [ThingPulse/esp8266-weather-station#41]
The blog goes on to add a DHT22 sensor and additional frames but none of the libraries or sketches seem similar to this.  It would be nice is you included an example sketch for the DHT22 frame to be displayed in the library.

**Comment by smithbrandt** [comment]
Not an example sketch, but here's the frame code I used with a DHT11.

`void drawInsideConditions(OLEDDisplay *display, OLEDDisplayUiState* state, int16_t x, int16_t y) {
  String t = String(dht.readTemperature(true)) + "°F";
  String h = String(dht.readHumidity()) + "%";

  int xt = (64 - (t.length() * 8)) / 2;
  int xh = ((64 - (h.length() * 8)) / 2) + 64;

  display->setTextAlignment(TEXT_ALIGN_LEFT);
  display->setFont(ArialMT_Plain_10);
  display->drawString(x + 49, y + 14, "Inside");
  display->drawString(x + 4, y + 26, "Temperature");
  display->drawString(x + 76, y + 26, "Humidity");
  display->setFont(ArialMT_Plain_16);
  display->drawString(x + 4, y + 38, t);
  display->drawString(x + 68, y + 38, h);
}`

**Comment by anthonyjclarke** [comment]
Try this, works great for me https://github.com/neptune2/esp8266-weather-station-oled-DST
