### ISSUE TITLE
Problem with the Ticker updates in WeatherStationDemoExtendedDST.ino

### ISSUE THREAD

**Issue by pagubg** [ThingPulse/esp8266-weather-station#44]
Hi,

I found that WeatherStationDemoExtendedDST.ino is not properly working on my esp.
The problem was that only setReadyForDHTUpdate was scheduled by the Ticker.
But in setup function we have ticker for both:
` ticker.attach(UPDATE_INTERVAL_SECS, setReadyForWeatherUpdate);`
` ticker.attach(60, setReadyForDHTUpdate);`
I've defined another variable for Ticker and that solved my issue.
Example:
` Ticker ticker; `
` Ticker weathertick;`
and
`ticker.attach(60, setReadyForDHTUpdate);`
 `weathertick.attach(UPDATE_INTERVAL_SECS, setReadyForWeatherUpdate);`

**Comment by terrag42** [comment]
I had the same problem, thanks for posting your workaround!

**Comment by AdaBill** [comment]
I also noticed the DHT was being updated BUT the Outside temp would stay the same until powered down.
I like the weather station and am glad for the latest update.. AND once I fixed this, it was Great again.

**Comment by anthonyjclarke** [comment]
Same issue here, was about to post the same issue, DHT updating, but not the WeatherForecast... will try the workaround

**Comment by WOnken** [comment]
Same problem here. Would be nice if this error could be updated...

**Comment by totof60** [comment]
thanks pagubg , it work for me

**Comment by smithbrandt** [comment]
Had the same issue, but didn't think to look here for a solution until after I spent two evenings banging on the code finally found the answer in the comments of a ticker demo file...

> Ticker is an object that will call a given function with a certain period.
  Each Ticker calls **one** function. You can have as many Tickers as you like,
  memory being the only limitation. 

> 

Oh well, it was actually fun figuring it out, and next time I'll look at the issues on GitHub before I waste my time.

**Comment by marcelstoer** [comment]
[Weather Underground closed their existing API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api) for non-paying customers on 2018-12-31. After [they stopped issuing free API keys](https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/) for low-volume personal use in May we migrated to OpenWeatherMap and [deprecated all WU code](https://github.com/ThingPulse/esp8266-weather-station#deprecation-notes) in this library.

We are now closing all WU-related issues and PRs.
