### ISSUE TITLE
errors in compilation

### ISSUE THREAD

**Issue by wizbrewery** [ThingPulse/esp8266-weather-station#6]
Hi,  great project,  thank you.  I'm using arduino 1.6.5 ide.  I notice that the following library has changed name ssd1306_i2c.h to ssd1306

I tried to download the previous version before the name change here https://github.com/squix78/esp8266-oled-ssd1306/releases/tag/1.0.1

but get the following compilation errors

Arduino: 1.6.5 (Windows 8.1), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

esp8266-weather-station.ino:33:19: warning: extra tokens at end of #include directive [enabled by default]
In file included from C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/esp8266_peri.h:24:0,
                 from C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/Arduino.h:38,
                 from C:\Users\waldy\Documents\Arduino\libraries\json-streaming-parser-master/JsonListener.h:28,
                 from esp8266-weather-station.ino:29:
C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/c_types.h:71:66: error: redefinition of 'const char ArialMT_Plain_10 []'
 #define ICACHE_RODATA_ATTR  **attribute**((section(".irom.text")))
                                                                  ^
C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/pgmspace.h:15:21: note: in expansion of macro 'ICACHE_RODATA_ATTR'
 #define PROGMEM     ICACHE_RODATA_ATTR
                     ^
C:\Users\waldy\Documents\Arduino\libraries\esp8266-oled-ssd1306-1.0.1/SSD1306Fonts.h:26:31: note: in expansion of macro 'PROGMEM'
 const char ArialMT_Plain_10[] PROGMEM = {
                               ^
In file included from esp8266-weather-station.ino:36:0:
C:\Users\waldy\Documents\Arduino\libraries\esp8266-oled-ssd1306-1.0.1/SSD1306Fonts.h:26:12: error: 'const char ArialMT_Plain_10 [2596]' previously defined here
 const char ArialMT_Plain_10[] PROGMEM = {
            ^
In file included from C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/esp8266_peri.h:24:0,
                 from C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/Arduino.h:38,
                 from C:\Users\waldy\Documents\Arduino\libraries\json-streaming-parser-master/JsonListener.h:28,
                 from esp8266-weather-station.ino:29:
C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/c_types.h:71:66: error: redefinition of 'const char ArialMT_Plain_16 []'
 #define ICACHE_RODATA_ATTR  **attribute**((section(".irom.text")))
                                                                  ^
C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/pgmspace.h:15:21: note: in expansion of macro 'ICACHE_RODATA_ATTR'
 #define PROGMEM     ICACHE_RODATA_ATTR
                     ^
C:\Users\waldy\Documents\Arduino\libraries\esp8266-oled-ssd1306-1.0.1/SSD1306Fonts.h:484:31: note: in expansion of macro 'PROGMEM'
 const char ArialMT_Plain_16[] PROGMEM = {
                               ^
In file included from esp8266-weather-station.ino:36:0:
C:\Users\waldy\Documents\Arduino\libraries\esp8266-oled-ssd1306-1.0.1/SSD1306Fonts.h:484:12: error: 'const char ArialMT_Plain_16 [5550]' previously defined here
 const char ArialMT_Plain_16[] PROGMEM = {
            ^
In file included from C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/esp8266_peri.h:24:0,
                 from C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/Arduino.h:38,
                 from C:\Users\waldy\Documents\Arduino\libraries\json-streaming-parser-master/JsonListener.h:28,
                 from esp8266-weather-station.ino:29:
C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/c_types.h:71:66: error: redefinition of 'const char ArialMT_Plain_24 []'
 #define ICACHE_RODATA_ATTR  **attribute**((section(".irom.text")))
                                                                  ^
C:\Users\waldy\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/pgmspace.h:15:21: note: in expansion of macro 'ICACHE_RODATA_ATTR'
 #define PROGMEM     ICACHE_RODATA_ATTR
                     ^
C:\Users\waldy\Documents\Arduino\libraries\esp8266-oled-ssd1306-1.0.1/SSD1306Fonts.h:942:31: note: in expansion of macro 'PROGMEM'
 const char ArialMT_Plain_24[] PROGMEM = {
                               ^
In file included from esp8266-weather-station.ino:36:0:
C:\Users\waldy\Documents\Arduino\libraries\esp8266-oled-ssd1306-1.0.1/SSD1306Fonts.h:942:12: error: 'const char ArialMT_Plain_24 [11797]' previously defined here
 const char ArialMT_Plain_24[] PROGMEM = {
            ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by squix78** [comment]
I think this issue should be fixed by now. Do you still have it or can we close the item?
