### ISSUE TITLE
Contribution: PHP convert images to raw ILI9341 bitstream (image proxy)

### ISSUE THREAD

**Issue by osos** [ThingPulse/esp8266-weather-station#61]
Please find attached my attempt to make a PHP "image proxy" for the ILI9341.

Basically the php-script takes any url as parameter gets and convert the image to a RGB565 raw format suitable for the ILI9341. simple file-caching included.

the first 16-bit = width of image, next 16-bit = height of image. the remaining bit are raw bitstream in RGR 565 format directly for the display.

Inside the php-script is a function to but into ESP8266 to directly stream the image from the imageproxy onto the ILI9341-based display.

[espimages.php.zip](https://github.com/squix78/esp8266-weather-station/files/925743/espimages.php.zip)

**Comment by osos** [comment]
The above enables this product:

![weatherstation](https://cloud.githubusercontent.com/assets/1785036/25091784/23af55c2-238b-11e7-8447-4dd01c1c9676.jpg)

Any image from the web can be viewed.

**Comment by lorol** [comment]
Hi, thank you for this contribution! 
FYI, here are similar converters:
1) [To RGB565 - like yours](http://www.petrucci.ch/arduino/?page=tft)
2) [To custom SQUIX 2-bit color format](http://web.295.ca/295forums/phpBB2/display.htm) 
I adapted the 1) to 2-bit version. It could be done from your php file as well ...
