### ISSUE TITLE
jsonlistener.h issue

### ISSUE THREAD

**Issue by gingerbread233** [ThingPulse/esp8266-weather-station#62]
When compiling the scetch, it alwasy says

C:\Users\xxxxxxx\Desktop\esp8266-weather-station-master\examples\WeatherStationDemo\WeatherStationDemo.ino:28:26: fatal error: JsonListener.h: No such file or directory

 #include <JsonListener.h>

                          ^

compilation terminated.

exit status 1

I searched your folder but the file is missing.

How can we fix this ?

**Comment by squix78** [comment]
You need to install the JsonStreamingParser library: https://github.com/squix78/json-streaming-parser

**Comment by gingerbread233** [comment]
Thank you, it worked, sorry for opening the issue, I´m new in arduino.
