### ISSUE TITLE
Cant upload sketch

### ISSUE THREAD

**Issue by kahlenberg** [ThingPulse/esp8266-weather-station#75]
Hi,

I have a Wemos [board ](https://de.aliexpress.com/item/Lolin-ESP32-OLED-wemos-for-Arduino-ESP32-OLED-WiFi-Modules-Bluetooth-Dual-ESP-32-ESP-32S/32807531243.html?isOrigTitle=true). There is no schematic no documentation, I write my problmes here, sory.
There are two buttons on board, EN and BOOT. I compile this project but can not upload sketch to board.
What should I do? I tried all combination of buttons, nothing worked. How can I programm this board?
USB-Serial driver installed correctly. There is a demo on board, I open terminal and it sends some information over serial port, so serial adapter works.

When I try to upload program, I receive always;

warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

Thanks.

**Comment by akeilox** [comment]
I dont have Wemos (yet) but had similar experience with one nodemcu unit (same architecture).

Disconnecting the cables (D0, D1 etc.) and trying to upload seemed to work. Would say give it a try.

**Comment by pftchal** [comment]
[part1.zip](https://github.com/ThingPulse/esp8266-weather-station/files/3108057/part1.zip)

this is part 1

**Comment by pftchal** [comment]
[part2.zip](https://github.com/ThingPulse/esp8266-weather-station/files/3108058/part2.zip)

this is part 2
