### ISSUE TITLE
Locale for current date

### ISSUE THREAD

**Issue by antonioag95** [ThingPulse/esp8266-weather-station#79]
Hello, thank you for your awesome code. Everything looks really nice and I love it! I have a question for you, as soon as an option to set locale for wundergroung exists, is there a way to set a locale for the current date? For example, today shows "Tue, 01 Aug 2017" which would be "Mar, 01 Ago 2017" in italian. Can it be done? Thank you very much!

**Comment by marcelstoer** [comment]
Dup of #50
