### ISSUE TITLE
Examples/README is missing XPT2046

### ISSUE THREAD

**Issue by suculent** [ThingPulse/esp8266-weather-station#81]
In the Getting started guide, there's list of libraries that needs to be updated. XPT2046 library by Paul Stoggregen is missing, while ESP8266 Weather library is only in README.

**Comment by marcelstoer** [comment]
You only need the XPT2046 lib for the color kit i.e. https://github.com/ThingPulse/esp8266-weather-station-color and this is listed in the current guide at https://docs.thingpulse.com/guides/wifi-color-display-kit/#install-libraries -> closing
