### ISSUE TITLE
Hourly forecast library - unexpected results

### ISSUE THREAD

**Issue by bill-orange** [ThingPulse/esp8266-weather-station#83]
The Hourly example's serial output is not the behavior I expected.  Wunderground Hourly produces 36 strings.  In other words, it looks 36 hours ahead.  The example displays only 24 hours of the 36 and omitting the 12 hours closes to current time.  Unfortunately,  These are the hours I need!

This does not appear to be easily 'fixable' in the example.  Setting WGHourly hourlies[24]; to [36] results in a crash.  Changing  for (int i = 0; i < 24; i++) to (int i = 35; i > 12; i--) without changing WGHourly.  results in no output.

I think this is a problem with the library code rather than with the example.

Also localization using state/ city works fine (as in the present example).  Localization using PWS also works fine,  I could not get ZMW to work at all.  This is not a big problem for me since the other two methods are okay (my weather station is KCAORANG21).

I should have been able to fix this these issues myself but so far I have not found the problems.

I am stumped.  Can you help?

**Comment by bill-orange** [comment]
These changes to WundergroundHourly.cpp fix my problem.  The returnFlag counter prevents the most current data from being overwritten.

void WundergroundHourly::doUpdate(WGHourly *hourlies, String url) {
  this->hourlies = hourlies;
  JsonStreamingParser parser;
  parser.setListener(this);
  **returnFlag = 0;**


void WundergroundHourly::value(String value) {
  **if (returnFlag >= 24) return;
  if (currentKey == "hour") {
    currentHour = value.toInt();
    returnFlag++;
    Serial.print(returnFlag);**

**Comment by mwick83** [comment]
I addressed the issue in PullRequest #91.
