### ISSUE TITLE
Field values wrong

### ISSUE THREAD

**Issue by Tokn59** [ThingPulse/esp8266-weather-station#85]
Hello, first of all, thank you for sharing your great code !!!

I have implemented the weathestation sketch, got a wundergroundAPI key and everything just works fine. However I get a wrong temp and humidity displayed. when activating the serial monitor during sketch compilation I get the following valus which are shown on the display as Outdoor Temp and Humidity : 
Requesting URL: /channels/67284/feeds.json?results=1&api_key=L2VIW20QVNZJBLAK
.
field1: 27.10
field2: 48.20

They are way too high. When I go to the Wunderground site and check my location it shows the correct temp which is approx 14 C ...

Any idea what is wrong ?

Thanks & Kind Regards,

Tony

**Comment by antonioag95** [comment]
Those values are not from Wunderground. Those values are from ThingSpeak (if not changed those values are from developer's sensors). Wunderground and ThingSpeak are two totally different services.

**Comment by Tokn59** [comment]
You are absolutely right ! Thank you for uyour response !!!
