### ISSUE TITLE
Use wunderground for (outdoor) climate information

### ISSUE THREAD

**Issue by squix78** [ThingPulse/esp8266-weather-station#9]
Hi Dani,
nice project! What about uploading outdoor sensor data to wunderground directly instead of tingspeak?
Then you could read and display your own data from wunderground (const String WUNDERGROUND_CITY = "pws:YOUR_WEATHERSTATION_ID";)
Would this work?

**Comment by piwrks** [comment]
I testet it putting WU-weather-station from my neighbour in. I get his data to my display.

**Comment by marcelstoer** [comment]
[Weather Underground closed their existing API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api) for non-paying customers on 2018-12-31. After [they stopped issuing free API keys](https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/) for low-volume personal use in May we migrated to OpenWeatherMap and [deprecated all WU code](https://github.com/ThingPulse/esp8266-weather-station#deprecation-notes) in this library.

We are now closing all WU-related issues and PRs.
