### ISSUE TITLE
smaller font size of DSEG7

### ISSUE THREAD

**Issue by cryptooth** [ThingPulse/esp8266-weather-station#90]
Is it possible to use smaller font size of DSEG7? Only one (21) size is available.

I want to use small DSEG7 fonts in some ticker. How can I generate 10-12-14-16 or 18 size of DSEG7?

Thanks in advance

**Comment by lorol** [comment]
Yes, it is possible:
A) You can draw from scratch one 8 symbol and make a font on given size yourself by [this](https://rawgit.com/lorol/esp8266-oled-ssd1306/master/resources/glyphEditor.html) tool
B) You can find a 7SEG system font and install it to your Linux or Windows PC, NetBeans IDE and JDK8 then use [this](https://github.com/lorol/esp8266-oled-ssd1306/tree/master/resources/FontConverterV3) project to compile a JAR that works like Squix' online generator but under your control.
C) You can check [this](https://forum.arduino.cc/index.php?topic=447956) tool as well to make manually or convert an existing font from other formats.
D) You can keep asking here-there Squix to answer you, or someone else eventually to generate exactly what you want :)
