### ISSUE TITLE
WundergroundHourly Hourlies has 24 index but FCTIME has 36 forecast hours

### ISSUE THREAD

**Issue by davidbadia** [ThingPulse/esp8266-weather-station#98]
Wunderground API feature: hourly has 36 FCTIME blocks. Forecast for the next 36 hours.
I think library is using field hour as an index but hour is 0 to 24 value.
Parsing is overwriting 12 = (36 - 24) records in hourly[index] structure contents. 
For instance, if now is 17:00 you get forecast hours:
18, 19, 20, 21, 22, 23 (today)
0, 1, 2, 3, 4, 5, 6 ,7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 (tomorrow)
0, 1, 2, 3, 4 ,5 (after tomorrow)
If you ask for hours: 3, 6, 9, 12 you get mixed values:
3 (after tomorrow), 6, 9, 12 (tomorrow)
A solution would be to limit parsing iterations through FCTIME to 24.

**Comment by mwick83** [comment]
That's what I addressed in PullRequest #91.

Cheers, Manuel

**Comment by davidbadia** [comment]
Hello Manuel, 
An alternative to limit parsed hours to 24 is to use 'epoch' field to built a index sorted by time for hourlies.
First: converting current hour with mm:ss = 00:00 to epoch time format.
Second: (epoch field value - current epoch) = index
or searching epoch by adding current epoch + 3600. This is ordered as is in json and is possible to read all 36 hours of forecast. Accesing by hour increment instead of hour value.
Best regards,
David

**Comment by marcelstoer** [comment]
[Weather Underground closed their existing API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api) for non-paying customers on 2018-12-31. After [they stopped issuing free API keys](https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/) for low-volume personal use in May we migrated to OpenWeatherMap and [deprecated all WU code](https://github.com/ThingPulse/esp8266-weather-station#deprecation-notes) in this library.

We are now closing all WU-related issues and PRs.
